// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLA1-XclfDXoMkuIejPlqIOISJwx2LfY',
    appId: '1:841867238413:web:d10c48fa9d49e02f724944',
    messagingSenderId: '841867238413',
    projectId: 'capyba-software',
    authDomain: 'capyba-software.firebaseapp.com',
    storageBucket: 'capyba-software.firebasestorage.app',
    measurementId: 'G-Y8MR2XYGRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YkDBR4Ao9fv4ewHxbE1ofRR6adhp86s',
    appId: '1:841867238413:android:1e31ebc59463c108724944',
    messagingSenderId: '841867238413',
    projectId: 'capyba-software',
    storageBucket: 'capyba-software.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvyH4mHAkUrHWVBSG2qvi4s-F59d0T6I',
    appId: '1:841867238413:ios:9ff7ac3d27f6c018724944',
    messagingSenderId: '841867238413',
    projectId: 'capyba-software',
    storageBucket: 'capyba-software.firebasestorage.app',
    iosClientId: '841867238413-mtl2ne3lplpjn25qt0trm77ghou3ernc.apps.googleusercontent.com',
    iosBundleId: 'com.example.capybaSoftwareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjvyH4mHAkUrHWVBSG2qvi4s-F59d0T6I',
    appId: '1:841867238413:ios:9ff7ac3d27f6c018724944',
    messagingSenderId: '841867238413',
    projectId: 'capyba-software',
    storageBucket: 'capyba-software.firebasestorage.app',
    iosClientId: '841867238413-mtl2ne3lplpjn25qt0trm77ghou3ernc.apps.googleusercontent.com',
    iosBundleId: 'com.example.capybaSoftwareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLA1-XclfDXoMkuIejPlqIOISJwx2LfY',
    appId: '1:841867238413:web:a2a4cccc1cd2f27d724944',
    messagingSenderId: '841867238413',
    projectId: 'capyba-software',
    authDomain: 'capyba-software.firebaseapp.com',
    storageBucket: 'capyba-software.firebasestorage.app',
    measurementId: 'G-JQWYZQLY96',
  );
}
